In [2]:
import numpy as np

In [3]:
my_series = [[10,20,30],[20,30,40],[40,50,60]]

In [5]:
sample_matrix_series = np.array(my_series)

In [6]:
sample_matrix_series

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [7]:
sample_matrix_series[0]

array([10, 20, 30])

In [8]:
sample_matrix_series[0][0]

10

In [9]:
sample_matrix_series[1][2]

40

In [11]:
sample_matrix_series[1,2]#diğer yazım

40

In [12]:
sample_matrix_series[0,0]#DİĞER YAZIM

10

In [14]:
sample_matrix_series[1:,2]

array([40, 60])

In [15]:
sample_matrix_series[2:,2]

array([60])

In [16]:
sample_matrix_series[0:,2]

array([30, 40, 60])

In [18]:
sample_matrix_series[2:,0]

array([40])

In [19]:
sample_matrix_series[2:,0:]

array([[40, 50, 60]])

In [20]:
sample_matrix_series[2:,1:]

array([[50, 60]])

In [21]:
sample_matrix_series[2:,2:]

array([[60]])

In [23]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [26]:
yeniListe

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [24]:
yeniMatrix = np.array(yeniListe)

In [25]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
yeniMatrix[[]]

array([], shape=(0, 5), dtype=int64)

In [28]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [29]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])