In [2]:
import numpy as np

In [3]:
new_series = np.arange(5,25)

In [4]:
new_series

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [5]:
new_series = np.random.randint(1,100,20)

In [8]:
new_series

array([13, 81, 94, 82, 23, 26, 96, 77, 69, 82, 69, 10, 35, 66, 71, 73, 45,
       20, 97, 89])

In [9]:
new_series > 24

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True])

In [10]:
new_series < 24

array([ True, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False])

In [11]:
new_series >= 24

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True])

In [12]:
new_series <= 24

array([ True, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False])

In [13]:
sonuc_series = new_series > 24

In [14]:
sonuc_series

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True])

In [15]:
new_series[sonuc_series]

array([81, 94, 82, 26, 96, 77, 69, 82, 69, 35, 66, 71, 73, 45, 97, 89])

In [16]:
series = new_series[sonuc_series]

In [17]:
series

array([81, 94, 82, 26, 96, 77, 69, 82, 69, 35, 66, 71, 73, 45, 97, 89])

In [18]:
type(series)

numpy.ndarray

In [19]:
new_series[new_series>24]

array([81, 94, 82, 26, 96, 77, 69, 82, 69, 35, 66, 71, 73, 45, 97, 89])

In [20]:
series = new_series[new_series > 24]

In [21]:
series

array([81, 94, 82, 26, 96, 77, 69, 82, 69, 35, 66, 71, 73, 45, 97, 89])

In [22]:
type(series)

numpy.ndarray

In [23]:
end_series = np.arange(0,24)

In [24]:
end_series

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
end_series + end_series

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [26]:
end_series

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
end_series + 8

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31])

In [29]:
end_series - 9

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14])

In [30]:
end_series * 5

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115])

In [32]:
end_series * end_series

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [33]:
end_series - end_series

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [34]:
end_series / 7

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ,
       2.14285714, 2.28571429, 2.42857143, 2.57142857, 2.71428571,
       2.85714286, 3.        , 3.14285714, 3.28571429])

In [35]:
end_series / end_series

/tmp/ipykernel_8540/2262169021.py:1: RuntimeWarning: invalid value encountered in divide
  end_series / end_series


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [36]:
np.sqrt(end_series)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [37]:
np.max(end_series)

23

In [38]:
np.min(end_series)

0

In [ ]:
#daha fazlası için numpy.org