In [1]:
import numpy as np

In [2]:
my_series = np.arange(0,15)

In [3]:
my_series

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
my_series[5]

5

In [5]:
my_series[3:5]

array([3, 4])

In [6]:
my_series[3:8] = -5 #eleman değiştirmek

In [7]:
my_series

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [8]:
deniz = np.arange(0,24)

In [9]:
deniz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
slicing_series = deniz[4:9]

In [11]:
slicing_series

array([4, 5, 6, 7, 8])

In [12]:
deniz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
slicing_series = 700

In [14]:
slicing_series

700

In [15]:
type(slicing_series)

int

In [16]:
slicing_series = deniz[4:9]

In [17]:
type(slicing_series)

numpy.ndarray

In [18]:
slicing_series[:]=700 #bütün elemanları değiştirme

In [19]:
slicing_series

array([700, 700, 700, 700, 700])

In [21]:
deniz #bu dizinin içindeki de değişti

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [22]:
sample_series = np.arange(0,24)

In [23]:
sample_series_copy = sample_series.copy()

In [24]:
sample_series_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
sample_series_copy_slicing = sample_series_copy[3:6]

In [26]:
sample_series_copy_slicing[:] = 800

In [27]:
sample_series_copy_slicing

array([800, 800, 800])

In [28]:
sample_series_copy

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [29]:
sample_series #değişim engellendi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])