In [2]:
import numpy as np

In [3]:
my_series = np.arange(50)

In [4]:
my_series

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
my_random = np.random.randint(0,80,10)

In [10]:
my_random

array([35, 11, 13, 23, 19, 32,  3, 19, 59, 70])

In [7]:
my_series.reshape(5,10) #yeniden şekillendir, istenilen boyut içinde #5 satır 10 kolon

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [8]:
my_series.max()

49

In [11]:
my_random.max()

70

In [12]:
my_random.min()

3

In [15]:
my_random.argmax() #max yer bulma

9

In [16]:
my_random.argmin() #min yer bulma #biir method

6

In [17]:
my_series.shape #bir özellik

(50,)

In [18]:
my_series

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
reshape_series = my_series.reshape(10,5)

In [20]:
reshape_series

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])